In [1]:
# read a lariac4 file / liDar
# python shapefile only reas shp or dbf
from laspy.file import File
from laspy import header
import numpy as np

lariac4_lidar = File('L4_6276_1842b.las', mode='r')

In [2]:
# Grab all of the points from the file.
point_records = lariac4_lidar.points

# Grab just the X dimension from the file, and scale it.

def scaled_x_dimension(las_file):
    x_dimension = las_file.X
    scale = las_file.header.scale[0]
    offset = las_file.header.offset[0]
    return(x_dimension*scale + offset)

scaled_x = scaled_x_dimension(lariac4_lidar)
scaled_x

array([6276400.16, 6276400.43, 6276400.55, ..., 6279016.78, 6279016.94,
       6279016.99])

In [9]:
# Find out what the point format looks like.
pointformat = lariac4_lidar.point_format
for spec in lariac4_lidar.point_format:
    print(spec.name)
# print(lariac4_lidar.point_format.xml())



X
Y
Z
intensity
flag_byte
classification_flags
classification_byte
user_data
scan_angle
pt_src_id
gps_time


In [10]:
#Lets take a look at the header also.
headerformat = lariac4_lidar.header.header_format
headerformat
for spec in headerformat:
    print(spec.name)

    #headerformat.x_min

file_sig
file_source_id
global_encoding
proj_id_1
proj_id_2
proj_id_3
proj_id_4
version_major
version_minor
system_id
software_id
created_day
created_year
header_size
data_offset
num_variable_len_recs
data_format_id
data_record_length
legacy_point_records_count
legacy_point_return_count
x_scale
y_scale
z_scale
x_offset
y_offset
z_offset
x_max
x_min
y_max
y_min
z_max
z_min
start_wavefm_data_rec
start_first_evlr
num_evlrs
point_records_count
point_return_count


In [3]:
# Header Information
Min = lariac4_lidar.header.min 
print(Min)  # info about min.x,min.y,min.z
Max = lariac4_lidar.header.max
print(Max) # info about max.x,max.y,max.zMax = inFile.header.max
lariac4_lidar

[6276400.0, 1844640.0, -619.16]
[6279039.99, 1847279.99, 1536.32]


In [48]:
# pull out x, y both min and max
# inFile.header.max[0]
print(lariac4_lidar.header.min, " ", lariac4_lidar.header.max)
# get_header_property(name)
X = lariac4_lidar.x  # only X data
print(X)
Y = lariac4_lidar.y # only Y data 
print(Y)

[6276400.0, 1844640.0, -619.16]   [6279039.99, 1847279.99, 1536.32]
[6276400.16 6276400.43 6276400.55 ... 6279016.78 6279016.94 6279016.99]
[1846989.31 1846988.63 1846987.78 ... 1844662.06 1844664.85 1844664.12]


In [20]:
# Grab all of the points from the file.
point_records = lariac4_lidar.points

# Grab just the X dimension from the file, and scale it.

def scaled_x_dimension(lariac4_lidar):
    x_dimension = lariac4_lidar.X
    scale = lariac4_lidar.header.scale[0]
    offset = lariac4_lidar.header.offset[0]
    return(x_dimension*scale + offset)

scaled_x = scaled_x_dimension(lariac4_lidar)
print(scaled_x)

[6276400.16 6276400.43 6276400.55 ... 6279016.78 6279016.94 6279016.99]


In [ ]:
# bounding box specified by file.header.max and file.header.min.

In [23]:
# [6276400.0, 1844640.0, -619.16]   [6279039.99, 1847279.99, 1536.32]

print("x: ", lariac4_lidar.x)

x:  [6276400.16 6276400.43 6276400.55 ... 6279016.78 6279016.94 6279016.99]


In [24]:
print("y ", lariac4_lidar.y)

y  [1846989.31 1846988.63 1846987.78 ... 1844662.06 1844664.85 1844664.12]


In [26]:
print(lariac4_lidar.X)

[627640016 627640043 627640055 ... 627901678 627901694 627901699]


In [27]:
print(lariac4_lidar.Y)

[184698931 184698863 184698778 ... 184466206 184466485 184466412]
